services:
  app:
    image: php:7.2-fpm-alpine
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html

  webserver:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
